# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-25 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190325_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='cardindex',
            name='id_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Category', verbose_name='Статус клиента'),
        ),
        migrations.AlterField(
            model_name='control',
            name='check_mark',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
