# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-25 05:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190325_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardindex',
            name='id_status',
        ),
        migrations.AddField(
            model_name='cardindex',
            name='id_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Category', verbose_name='Категория клиента'),
            preserve_default=False,
        ),
    ]
