# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-25 05:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190325_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardindex',
            old_name='id_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='cardindex',
            old_name='id_client',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='cardindex',
            old_name='id_control',
            new_name='control',
        ),
    ]
