# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-25 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190325_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardindex',
            name='ipd',
            field=models.IntegerField(default=1, max_length=20, verbose_name='Индивидуальное порядковое дело'),
            preserve_default=False,
        ),
    ]
