# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-25 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_cardindex_ipd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardindex',
            name='control',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Control', verbose_name='Движение ЛД'),
        ),
    ]
