# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-29 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190329_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardindex',
            name='ipd',
        ),
        migrations.AddField(
            model_name='client',
            name='ipd',
            field=models.IntegerField(default=1, verbose_name='Индивидуальное порядковое дело'),
            preserve_default=False,
        ),
    ]
