# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-02 00:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190329_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardindex',
            name='info',
            field=models.CharField(default=1, max_length=200, verbose_name='Движение ЛД по другим УСЗН'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cardindex',
            name='spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UsersProfile', verbose_name='Движение ЛД по специалистам'),
        ),
    ]
