# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-02 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190402_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardindex',
            name='info',
            field=models.CharField(blank=True, max_length=200, verbose_name='Движение ЛД по другим УСЗН'),
        ),
    ]
