# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-02 01:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20190402_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardindex',
            name='control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Control', verbose_name='Статус ЛД'),
        ),
        migrations.AlterField(
            model_name='cardindex',
            name='spec',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.UsersProfile', verbose_name='Движение ЛД по специалистам'),
        ),
    ]
