# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-04 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20190402_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='cardindex',
            name='category',
            field=models.ForeignKey(help_text='Категория клиента', on_delete=django.db.models.deletion.CASCADE, to='main.Category', verbose_name='Категория клиента'),
        ),
        migrations.AlterField(
            model_name='cardindex',
            name='client',
            field=models.ForeignKey(help_text='Клиент', on_delete=django.db.models.deletion.CASCADE, to='main.Client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='cardindex',
            name='control',
            field=models.ForeignKey(help_text='Статус ЛД', on_delete=django.db.models.deletion.CASCADE, to='main.Control', verbose_name='Статус ЛД'),
        ),
        migrations.AlterField(
            model_name='cardindex',
            name='info',
            field=models.CharField(blank=True, help_text='Движение по др. УСЗН.', max_length=200, verbose_name='Движение ЛД по другим УСЗН'),
        ),
        migrations.AlterField(
            model_name='cardindex',
            name='ipd',
            field=models.IntegerField(help_text='ИПД', verbose_name='Индивидуальное порядковое дело'),
        ),
        migrations.AlterField(
            model_name='cardindex',
            name='spec',
            field=models.ForeignKey(blank=True, default='в архиве', help_text='Движение ЛД', on_delete=django.db.models.deletion.CASCADE, to='users.UsersProfile', verbose_name='Движение ЛД по специалистам'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(help_text='Категория клиента', max_length=40),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(help_text='Адрес проживания', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='bday',
            field=models.DateField(help_text='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(help_text='Имя', max_length=30),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(help_text='Фамилия', max_length=30),
        ),
        migrations.AlterField(
            model_name='client',
            name='middle_name',
            field=models.CharField(help_text='Отчество', max_length=30),
        ),
        migrations.AlterField(
            model_name='control',
            name='check_mark',
            field=models.CharField(help_text='Движение ЛД', max_length=30),
        ),
        migrations.AddField(
            model_name='query',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CardIndex'),
        ),
    ]
