# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-04 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('main', '0016_auto_20190404_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='query',
            new_name='query_client',
        ),
        migrations.AddField(
            model_name='query',
            name='query_spec',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.UsersProfile'),
            preserve_default=False,
        ),
    ]
