# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-05 04:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20190404_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='query_date',
            field=models.DateTimeField(default=None, help_text='Время запроса', null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='query_ld',
            field=models.IntegerField(default=0, help_text='Статус запроса'),
        ),
        migrations.AlterField(
            model_name='query',
            name='query_client',
            field=models.ForeignKey(help_text='Личное дело', on_delete=django.db.models.deletion.CASCADE, to='main.CardIndex'),
        ),
        migrations.AlterField(
            model_name='query',
            name='query_spec',
            field=models.ForeignKey(help_text='Специалист', on_delete=django.db.models.deletion.CASCADE, to='users.UsersProfile'),
        ),
    ]
