# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-05 04:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20190405_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='query_client',
            field=models.ForeignKey(blank=True, help_text='Личное дело', on_delete=django.db.models.deletion.CASCADE, to='main.CardIndex'),
        ),
        migrations.AlterField(
            model_name='query',
            name='query_spec',
            field=models.ForeignKey(blank=True, help_text='Специалист', on_delete=django.db.models.deletion.CASCADE, to='users.UsersProfile'),
        ),
    ]
