# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-05 04:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20190405_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardindex',
            name='spec',
            field=models.ForeignKey(blank=True, default='в архиве', help_text='Движение ЛД', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UsersProfile', verbose_name='Движение ЛД по специалистам'),
        ),
    ]
