# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-08 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20190405_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='query_ld',
            field=models.BooleanField(default=False, help_text='Статус запроса'),
        ),
    ]
