# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-16 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20190408_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardindex',
            name='spec',
            field=models.ForeignKey(blank=True, help_text='Движение ЛД', on_delete=django.db.models.deletion.CASCADE, to='users.UsersProfile', verbose_name='Движение ЛД по специалистам'),
        ),
        migrations.AlterField(
            model_name='query',
            name='query_client',
            field=models.ForeignKey(help_text='* Личное дело', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.CardIndex'),
        ),
        migrations.AlterField(
            model_name='query',
            name='query_date',
            field=models.DateField(default=None, help_text='* Дата запроса (01.01.2019)', null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='query_ld',
            field=models.BooleanField(default=False, help_text='* Статус запроса'),
        ),
        migrations.AlterField(
            model_name='query',
            name='query_spec',
            field=models.ForeignKey(help_text='* Специалист', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UsersProfile'),
        ),
    ]
